#!/usr/bin/env python3
'''venv_bootstrapper.py: uses virtualenv bootstrap functionality
    Sets up basic requirements for any Prosper project
    https://virtualenv.pypa.io/en/stable/reference/?highlight=bootstrap#creating-your-own-bootstrap-scripts'''

from os import path
import sys
from configparser import ConfigParser, ExtendedInterpolation

import virtualenv
import plumbum as pb
#from plumbum import local, path

CURRENT_DIR = path.abspath(path.dirname(__file__))
CONFIG_PATH = path.join(CURRENT_DIR, 'bootstrap.cfg')

def get_config(config_file=CONFIG_PATH):
    '''parse config file for global vars'''
    local_config = ConfigParser(
        interpolation=ExtendedInterpolation(),
        allow_no_value=True,
        delimiters=('='),
        inline_comment_prefixes=('#')
    )

    try:
        with open(config_file, 'r') as cfg_filehandle:
            local_config.read_file(cfg_filehandle)

        return local_config
    except Exception as error_msg:
        print(
            'EXCEPTION: unable to parse config file' + \
            '\r\texception={0}'.format(error_msg) + \
            '\r\tconfig_file={0}'.format(config_file)
        )
        exit(-1)

CONFIG = get_config()

###   vv AUTOGENERATED SCRIPT SEED vv   ###
### NOTE: block not linted              ###
### Extend EXTRA_TEXT over code block   ###
### !!ALL PASSED IN VALUES ARE STATIC!! ###

EXTRA_TEXT = '''
import pip
import platform
import site

def extend_parser(parser):
    """extra CLI args for adjusting parser"""
    pass

def adjust_options(option, args):
    """TODO: IDK ¯\_(ツ)_/¯"""
    pass

def after_install(options, home_dir):
    """actual venv bootstrap logic goes here"""
    pass
'''.format(
    None
)

###   ^^ AUTOGENERATED SCRIPT SEED ^^   ###


def main():
    '''runs create_boostrap_script functionality and spits out new virtualenv script'''
    bootstrap_script = virtualenv.create_bootstrap_script(
        EXTRA_TEXT,
        python_version=CONFIG.get('environment', 'python_version')
    )

    result_script = CONFIG.get('bootstrap', 'result_script_name')
    result_path = CONFIG.get('bootstrap', 'result_path')

    result_abspath = None
    if '..' in result_path:
        pb.local.cwd.chdir(CURRENT_DIR)
        result_abspath = pb.path.local.LocalPath(result_path)
    else:
        result_abspath = pb.local.path(result_path)
    result_abspath.mkdir()
    bootstrap_path = result_abspath / result_script #Plumbum maps __div__ to join()
    result_abspath = pb.path.local.LocalPath(bootstrap_path)

    current_text = ''
    if result_abspath.is_file():
        print('--PULLING EXISTING BOOTSTRAP SCRIPT--')
        with open(result_abspath, 'r') as filehandle:
            current_text = filehandle.read()
    else:
        print('--NO BOOTSTRAP FOUND--')

    if current_text == bootstrap_script:
        print('--NO UPDATE BOOTSTRAP SCRIPT--')
    else:
        print('--UPDATING BOOTSTRAP SCRIPT--')
        with open(result_abspath, 'w') as filehandle:
            filehandle.write(bootstrap_script)


if __name__ == '__main__':
    main()


